# Generated by Django 3.1.5 on 2021-01-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=100, verbose_name='Название компании')),
                ('description_company', models.TextField(verbose_name='Описание компании')),
                ('rating_company', models.IntegerField(verbose_name='Рейтинг компании')),
                ('id_reviews', models.IntegerField(verbose_name='ID отзыва')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_myself', models.TextField(verbose_name='Обо мне(пользователе)')),
                ('position_worker', models.TextField(verbose_name='Должность')),
                ('work_experience', models.IntegerField(verbose_name='Опыт работы (в годах)')),
                ('id_user', models.IntegerField(verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='Vacancies_cities',
            fields=[
                ('id_city', models.AutoField(primary_key=True, serialize=False)),
                ('name_cities', models.CharField(max_length=55, verbose_name='Название города')),
                ('quantity_vacancies', models.IntegerField(verbose_name='Количество актуальных ваансий')),
                ('id_vacancies', models.IntegerField(verbose_name='ID вакансии')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_vacancy', models.CharField(max_length=100, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('salary_of_mounth', models.IntegerField(verbose_name='Заработная плата (руб/мес)')),
                ('graphic_of_work', models.CharField(max_length=255, verbose_name='График работы/занятость')),
                ('id_company', models.IntegerField(verbose_name='ID компании')),
                ('id_summary', models.IntegerField(verbose_name='ID резюме')),
                ('id_vacancies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_work.vacancies_cities')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=55, verbose_name='Имя пользователя')),
                ('surname_user', models.CharField(max_length=255, verbose_name='Фамилия пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('date_register', models.TimeField(verbose_name='Дата регистрации')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_work.summary')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AddField(
            model_name='summary',
            name='id_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_work.vacancies'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=155, verbose_name='Фамилия пользователя')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок отзыва')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('id_reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_work.companies')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='companies',
            name='id_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_work.vacancies'),
        ),
    ]
